codecov:
  require_ci_to_pass: true

ignore:
  - "contracts/deployed/**"
  - "contracts/external/**"
  - "contracts/traits/**"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 60% # 95% goal
        threshold: 10% # 5% goal
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: true
    patch:
      default:
        target: 90%
        threshold: 10% # 5% goal
        base: auto
        if_ci_failed: error
        only_pulls: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
