name: Contract Review

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # allow running manually
  workflow_dispatch:

jobs:
  test-contracts:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
      - name: "Verify test file for each contract file"
        run: bash ./tests/check-test-coverage.sh
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: "Prep CI"
        run: npm ci
      - name: "Execute unit tests"
        run: npm run test:report
      - name: "Upload code coverage"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
          verbose: true
      - name: "Celebrate the win"
        run: bash ./tests/chadsay.sh Looking good